name: vcr

ghc-options: -Wall

default-extensions:
  - BlockArguments

dependencies:
  - base == 4.*
  - bytestring
  - text
  - filepath
  - directory
  - network-uri
  - case-insensitive
  - http-types
  - http-client
  - yaml
  - HUnit

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - mockery
      - http-client-tls
    cpp-options: -DTEST
    build-tools: hspec-discover
