name: vcr

ghc-options: -Wall

when:
  condition: impl(ghc < 9.4)
  ghc-options: -Wno-unticked-promoted-constructors

defaults: sol/ghc2024@v0.1.0

default-extensions:
  - BlockArguments
  - NoImplicitPrelude

dependencies:
  - base == 4.*
  - bytestring
  - text
  - filepath
  - directory
  - network-uri
  - case-insensitive
  - http-types
  - http-client
  - yaml
  - HUnit
  - containers

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
      - mockery
      - http-client-tls
    cpp-options: -DTEST
    build-tools: hspec-discover
