name: vcr

dependencies:
  - base == 4.*
  - bytestring
  - text
  - filepath
  - directory
  - network-uri
  - case-insensitive
  - http-types
  - http-client
  - yaml
  - HUnit

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - vcr
      - hspec
      - mockery
      - http-client-tls
    build-tools: hspec-discover
