resolver: lts-22.38
require-stack-version: ">=3.1"
compiler-check: newer-minor
packages:
  - .

extra-deps:
  - github: assertible/http-client
    commit: assertible-http-client-0.7.17
    subdirs:
      - http-client
      - http-conduit
